return {
	"nvim-lualine/lualine.nvim",
	"kyazdani42/nvim-web-devicons",
	"kyazdani42/nvim-tree.lua",
	"goolord/alpha-nvim",
	"akinsho/toggleterm.nvim",
	"nvim-lua/plenary.nvim",
	"nvim-telescope/telescope.nvim",
	"nvim-telescope/telescope-ui-select.nvim",
	{ "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
	"neovim/nvim-lspconfig",
	"hrsh7th/nvim-cmp",
	"hrsh7th/cmp-nvim-lsp",
	"saadparwaiz1/cmp_luasnip",
	"L3MON4D3/LuaSnip",
	"terrortylor/nvim-comment",
	"ojroques/nvim-lspfuzzy",
	"junegunn/fzf",
	"junegunn/fzf.vim",
	"marko-cerovac/material.nvim",
	"bluz71/vim-nightfly-guicolors",
	"bluz71/vim-moonfly-colors",
	"folke/todo-comments.nvim",
	"blacktrub/neovim-typer",
	"kevinhwang91/nvim-bqf",
	"bhurlow/vim-parinfer",
	"folke/trouble.nvim",
	"folke/neodev.nvim",
	"williamboman/mason.nvim",
	"williamboman/mason-lspconfig.nvim",
	"jose-elias-alvarez/null-ls.nvim",
	"jay-babu/mason-null-ls.nvim",
	"jay-babu/mason-nvim-dap.nvim",
	"mfussenegger/nvim-dap",
	"rcarriga/nvim-dap-ui",
	"mfussenegger/nvim-dap-python",
	"leoluz/nvim-dap-go",
	"ThePrimeagen/harpoon",
	"APZelos/blamer.nvim",
	"chentoast/marks.nvim",
	"sindrets/diffview.nvim",
	"ray-x/lsp_signature.nvim",
	"EdenEast/nightfox.nvim",
	"folke/neoconf.nvim",
	{ "blacktrub/stay-centered.nvim", dev = true },
	{ "echasnovski/mini.move", version = "*" },
	{ "echasnovski/mini.splitjoin", version = "*" },
	{ "blacktrub/telescope-godoc.nvim", dev = true },
	{ "phaazon/hop.nvim", branch = "v2" },
}
